FROM python:3.7-slim

RUN mkdir /app
WORKDIR /app

COPY requirements-api.txt ./requirements.txt
RUN pip install -r ./requirements.txt

COPY api/elastic/evaluate_score.py ./elastic/
COPY api/app.py api/student.py api/mentor.py api/wsgi.py api/gunicorn.sh ./

RUN chmod +x /app/gunicorn.sh
CMD sleep 5m
